### ISSUE TITLE
[Suggestion] - Filter results before loading them on screen. Animation is a little jarring at times.

### ISSUE THREAD

**Issue by Bengejd** [dpw1/youtube-filter#1]
Just wanted to start off by saying, great work on the extension. I've tried it out personally, and enjoy what you've put together so far. But, a suggestion that I have would be to block the network request from loading all together, instead of having the fancy animation remove results from the screen, as if you're filtering a lot of information, it can be jarring and hard to focus.

If you look in your network tab, you can see the video request times are shown through the following path in the `results?search_query=...` file:

`[1].response.continuationContents.itemSectionContinuation.contents[""0""].videoRenderer.lengthText.simpleText`. This would cut down on unnecessary requests, and IMO, would be more user friendly.

**Comment by dpw1** [comment]
thank you for the kind words!

Currently, the only way I have found to get a youtube video's length is by accesing its value in the DOM via the `.ytd-thumbnail-overlay-time-status-renderer` selector and it takes a little bit to be loaded.

Do you think there are other ways to get this value before it is rendered to the DOM?

**Comment by Bengejd** [comment]
Yeah, I actually linked you the network file path in my original comment

**Comment by dpw1** [comment]
Oops, sorry about that!

I confess I'm still not quite sure how to access that via Javascript though. Would you please give me some hint on this?

A bit off topic, I was able to find multiple objects at `window` starting with yt(something). Some of them may contain info about all the displayed videos!

**Comment by dpw1** [comment]
Found it!

`window["ytInitialData"].contents.twoColumnSearchResultsRenderer.primaryContents.sectionListRenderer.contents[0].itemSectionRenderer.contents`

This object contain accurate and instant information of all videos. That is amazing. I will play around with it.

Thank you!

**Comment by Bengejd** [comment]
No problem! Glad I could help :)

**Comment by dpw1** [comment]
Hey @Bengejd , I hope you're doing well!

After a long time I decided to return to this project. I'm creating a new repository and starting from scratch with webpack.

Anyhow, I came across a situation and thought I'd ask if you have any ideas how I can move through this:

I managed to access the Youtube object with the data for timestamps. The issue is that it's huge and deeply nested. [Here is an example.](https://gist.github.com/dpw1/9cecc864dbf80ea66b1698b9c588495f)

I need to find a way to access all keys with the name of "videoRenderer" and add them to a single array of objects, but I'm stuck on this. Do you have any suggestions?

Thank you!

**Comment by dpw1** [comment]
Update: I found a solution after asking it on [stackoverflow!](https://stackoverflow.com/questions/61809878/finding-all-keys-with-specific-name-within-deeply-nested-json/61810447#61810447)

I'll keep you updated about the new version, it's much faster than the previous one.
